### ISSUE TITLE
some accounts not showing friends in mobile version

### ISSUE THREAD

**Issue by sefabey** [narkopolo/fb_friend_list_scraper#3]
This is a hard issue to describe as it might be FB related. There are some accounts whose friends are not visible on `m.facebook.com/username/friends` which displays no friends to show. When the URL is changed to `www.facebook.com/username/friends` the friend list becomes visible. Any ideas?

One idea could be using the web version instead of the mobile one but that will probably need a refactor.

**Comment by n0kovo** [comment]
That is not something I have experienced myself, but definitely something that should be investigated. The reason the script is using the mobile version, is that the regular version is many times more complex and dynamic in its markup and a huge hassle to work with.

**Comment by sefabey** [comment]
Yeah, I can imagine that being the case. Be interesting if you can replicate on your end.

**Comment by n0kovo** [comment]
Is this still an issue for you with the latest version?

**Comment by n0kovo** [comment]
Closing due to lack of communication
