### ISSUE TITLE
won't load with pyopenssl update, force install old version and it works?

### ISSUE THREAD

**Issue by smarmitako** [narkopolo/fb_friend_list_scraper#6]
First, forgive the lack of correct terminology - I'm a journalist and barely know my way around this stuff.

Running after install gave an error:

 AttributeError: module 'OpenSSL.SSL' has no attribute 'SSLv2_METHOD'

Turns out pyopenssl 22.1.0 has Backward-incompatible changes: Remove support for SSLv2 and SSLv3

forced install of 22.0.0 and now it works!

**Comment by n0kovo** [comment]
Hey @smarmitako, sorry for the late reply. Thanks for opening an issue! I'm glad you got it working. I'll update the requirements.

**Comment by SpiritGun91** [comment]
![Screenshot_20230724-013203_crDroid Home](https://github.com/n0kovo/fb_friend_list_scraper/assets/101740573/e762af63-fb17-4ba5-91c7-f1d6a83a8f31)
I installed pyopenssl 22.0.0 and got this error.

**Comment by SpiritGun91** [comment]
It worked for me once I installed cryptography==38.0.4 after installing pyopenssl==22.0.0
