### ISSUE TITLE
AttributeErro

### ISSUE THREAD

**Issue by shaw1475963** [narkopolo/fb_friend_list_scraper#7]
AttributeError: module 'OpenSSL.SSL' has no attribute 'SSLv2_METHOD'

**Comment by n0kovo** [comment]
Yeah you're going to have to provide some more details than that mate.

**Comment by n0kovo** [comment]
https://www.google.com/search?q=AttributeError:+module+%27OpenSSL.SSL%27+has+no+attribute+%27SSLv2_METHOD%27+site:stackoverflow.com

**Comment by n0kovo** [comment]
#6
